### PR TITLE
Catch SIGINT and SIGTERM and set fan profile to optimal before quitting

### PR DESCRIPTION
**Pull request by ghost**
If this script is terminated using ctrl-c etc., then the fans continue to run at the last speed setting, instead of reverting back to being controlled by the BMC. This change makes sure the fan profile gets reset to "optimal" before quitting.

### CODE REVIEW

**Comment by ghost** [comment]
I've also updated the README.md to remove mention of the borg script, since it was deleted several months ago.

**Comment by khorton** [comment]
Thanks for your patches.  I'll study them and do local testing.

I've never had git pull request before, so it may take me some time to figure out the best way to accept your proposed changes.

Please be patient.

Thanks,

Kevin

**Comment by khorton** [comment]
As you can probably tell from looking at the code, I am a very amateur, self-taught programmer.  Until now, I was not aware that it was possible to define how a Perl program would respond to various POSIX signals.  

I agree that if the fan control script terminates, we want to put the IPMI fan mode in a safe state, so the motherboard can take control.

You propose to catch INT and TERM.  Looking at "man signal", there are many other signals that would lead to the script being terminated.  I haven't yet found anything that tells me if we should attempt to explicitly catch all these, or whether they all get funneled into INT or TERM signals, and your proposed change is thus complete.  Do you have any insight into this question?

Thanks - Kevin

**Comment by ghost** [comment]
From looking at https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html#Termination-Signals the only other one we might want to handle is SIGHUP.

**Comment by khorton** [comment]
I added code to handle SIGHUP to your changes, and tested by killing script with Ctrl-C.  The fan mode was reset to Optimal.  SIGTERM and SIGHUP were not tested.

Thanks for identifying the issue and proposing the fix.

**Pull request merged**
